### ISSUE TITLE
nfdhcpd_0.7_all.deb crashes regularly

### ISSUE THREAD

**Issue by thresheek** [davedoesdev/nfdhcpd#1]
I'm using the pre-built package from the dist/ and every once in a while I see nfdhcpd crashing with:

2015-06-22 19:23:59,877 INFO   Cleaning up
2015-06-22 19:23:59,921 INFO   Cleanup finished
2015-06-22 19:23:59,964 CRITICAL Traceback (most recent call last):
  File "/usr/sbin/nfdhcpd", line 1620, in <module>
    proxy.serve()
  File "/usr/sbin/nfdhcpd", line 1383, in serve
    self._serve()
  File "/usr/sbin/nfdhcpd", line 1422, in _serve
    self.notifier.process_events()
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 1295, in process_events
    self._default_proc_fun(revent)
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 937, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 662, in **call**
    return meth(event)
  File "/usr/sbin/nfdhcpd", line 372, in process_IN_DELETE
    self.server.remove_iface(event.name)
  File "/usr/sbin/nfdhcpd", line 831, in remove_iface
    del self.clients[self.rev_clients[iface]]
KeyError: '52:54:00:56:e7:c3'

Traceback (most recent call last):
  File "/usr/sbin/nfdhcpd", line 1620, in <module>
    proxy.serve()
  File "/usr/sbin/nfdhcpd", line 1383, in serve
    self._serve()
  File "/usr/sbin/nfdhcpd", line 1422, in _serve
    self.notifier.process_events()
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 1295, in process_events
    self._default_proc_fun(revent)
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 937, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 662, in **call**
    return meth(event)
  File "/usr/sbin/nfdhcpd", line 372, in process_IN_DELETE
    self.server.remove_iface(event.name)
  File "/usr/sbin/nfdhcpd", line 831, in remove_iface
    del self.clients[self.rev_clients[iface]]
KeyError: '52:54:00:56:e7:c3'

**Comment by davedoesdev** [comment]
@thresheek Thanks for letting me know. I hope to get back to nfdhcpd in the next couple of weeks.

**Comment by davedoesdev** [comment]
@thresheek are you using `NOTIFY_PORT` / `NOTIFY_IP` in your binding file?

Would you mind attaching `/var/log/nfdhcpd/nfdhcpd.log` ?

**Comment by davedoesdev** [comment]
Hi @thresheek Would you mind trying `nfdhcpd_0.10_all.deb`. Hopefully `remove_iface` should be more robust now.

**Comment by thresheek** [comment]
No I'm not using NOTIFY_PORT / NOTIFY_IP in binding files.

I'll try _0.10 and see how it goes for a few days.

Thanks @davedoesdev for looking into this, much appreciated!

**Comment by davedoesdev** [comment]
@thresheek how's it holding up?

**Comment by thresheek** [comment]
@davedoesdev So far so good, I did not experience any nfdhcpd crashes using the package provided on ubuntu 14.04.

Thanks a lot! I guess this fixes the issue.
